baseURL = 'https://my-art-site-ashen.vercel.app/'
languageCode = 'zh-cn'
title = 'bluesquare'
theme = 'gokarna'

[params]
  description = "个人博客"
  avatarURL = "/images/avatar.jpg"
  avatarSize = "size-m"
  avatarAltText = "My Avatar"

  showThemeSwitcher = true
  showPostsOnHomePage = "recent"
  numberPostsOnHomePage = 5

  [[params.socialIcons]]
    name = "X"
    url = "https://x.com/bluesquare1668" # 建议写完整链接